{{ if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}
{{- end -}}
