{{- if .Values.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
      ## mut be quoted: https://github.com/kubernetes/kubernetes/issues/82296
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - {{ .Values.host | quote }}
    - {{ printf "*.%s" .Values.host | quote }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
  - host: {{ printf "*.%s" .Values.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
{{- end -}}
