apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    name: web
    targetPort: {{ .Values.image.port }}
    protocol: TCP
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
