import type { ResourceIdentifier } from '../../ldp/representation/ResourceIdentifier';
import { getLoggerFor } from '../../logging/LogUtil';
import { BadRequestHttpError } from '../../util/errors/BadRequestHttpError';
import { NotFoundHttpError } from '../../util/errors/NotFoundHttpError';
import { joinFilePath, decodeUriPathComponents } from '../../util/PathUtil';

const logger = getLoggerFor('MapperUtil');

/**
 * Get the absolute file path based on the rootFilepath of the store.
 * @param rootFilepath - The root file path.
 * @param path - The relative file path.
 * @param identifier - Optional identifier to add to the path.
 *
 * @returns Absolute path of the file.
 */
export const getAbsolutePath = (rootFilepath: string, path: string, identifier = ''): string =>
  joinFilePath(rootFilepath, path, identifier);

/**
 * Strips the baseRequestURI from the identifier and checks if the stripped base URI matches the store's one.
 * @param baseRequestURI - Base URL for requests.
 * @param identifier - Incoming identifier.
 *
 * @throws {@link NotFoundHttpError}
 * If the identifier does not match the baseRequestURI path of the store.
 *
 * @returns A string representing the relative path.
 */
export const getRelativePath = (baseRequestURI: string, identifier: ResourceIdentifier): string => {
  if (!identifier.path.startsWith(baseRequestURI)) {
    logger.warn(`The URL ${identifier.path} is outside of the scope ${baseRequestURI}`);
    throw new NotFoundHttpError();
  }
  return decodeUriPathComponents(identifier.path.slice(baseRequestURI.length));
};

/**
 * Check if the given relative path is valid.
 *
 * @throws {@link BadRequestHttpError}
 * If the relative path is invalid.
 *
 * @param path - A relative path, as generated by {@link getRelativePath}.
 * @param identifier - A resource identifier.
 */
export const validateRelativePath = (path: string, identifier: ResourceIdentifier): void => {
  if (!path.startsWith('/')) {
    logger.warn(`URL ${identifier.path} needs a / after the base`);
    throw new BadRequestHttpError('URL needs a / after the base');
  }

  if (path.includes('/..')) {
    logger.warn(`Disallowed /.. segment in URL ${identifier.path}.`);
    throw new BadRequestHttpError('Disallowed /.. segment in URL');
  }
};
