import arrayifyStream from 'arrayify-stream';
import type { Quad } from '@rdfjs/types';
import type { Representation } from '../http/representation/Representation';
import type { ResourceIdentifier } from '../http/representation/ResourceIdentifier';
import type { WebIdStore } from '../identity/interaction/webid/util/WebIdStore';
import { INTERNAL_QUADS } from '../util/ContentTypes';
import { BadRequestHttpError } from '../util/errors/BadRequestHttpError';
import { createErrorMessage } from '../util/errors/ErrorUtil';
import { ForbiddenHttpError } from '../util/errors/ForbiddenHttpError';
import { trimTrailingSlashes } from '../util/PathUtil';
import { cloneRepresentation } from '../util/ResourceUtil';
import { SOLID } from '../util/Vocabularies';
import type { Conditions } from './conditions/Conditions';
import type { RepresentationConverter } from './conversion/RepresentationConverter';
import { PassthroughStore } from './PassthroughStore';
import type { ChangeMap, ResourceStore } from './ResourceStore';

/**
 * Guards the profile card of WebIDs registered on this server.
 *
 * The location of these cards is given by the `relativeWebIdPaths` parameter,
 * which lists the relative paths (including fragment) that are used for the
 * WebIDs generated by this server, e.g. `/profile/card#me`. Multiple paths can
 * be provided to also cover WebIDs generated with a previous configuration.
 * Whether a document is actually protected is always verified against the
 * {@link WebIdStore}, so only WebIDs that are registered to an account are
 * guarded, independent of the storage backend used.
 */
export class ProfileCardGuard extends PassthroughStore {
  private readonly webIdStore: WebIdStore;
  private readonly baseUrl: string;
  private readonly converter: RepresentationConverter;
  private readonly relativeWebIdPaths: string[];

  /**
   * @param source - Store wrapped by this guard.
   * @param webIdStore - Store tracking which WebIDs are registered to accounts.
   * @param baseUrl - Base URL of the server, used to verify the `solid:oidcIssuer` triple.
   * @param converter - Converts incoming representations to quads for validation.
   * @param relativeWebIdPaths - Relative paths (including fragment) of generated WebIDs,
   *                             e.g. `/profile/card#me`.
   */
  public constructor(
    source: ResourceStore,
    webIdStore: WebIdStore,
    baseUrl: string,
    converter: RepresentationConverter,
    relativeWebIdPaths: string[],
  ) {
    super(source);
    this.webIdStore = webIdStore;
    this.baseUrl = trimTrailingSlashes(baseUrl);
    this.converter = converter;
    this.relativeWebIdPaths = relativeWebIdPaths;
  }

  public async setRepresentation(
    identifier: ResourceIdentifier,
    representation: Representation,
    conditions?: Conditions,
  ): Promise<ChangeMap> {
    await this.validateCard(identifier, representation);
    return this.source.setRepresentation(identifier, representation, conditions);
  }

  public async addResource(
    container: ResourceIdentifier,
    representation: Representation,
    conditions?: Conditions,
  ): Promise<ChangeMap> {
    // The final URL of a new resource is determined by the backend,
    // so only validate if it is already known. A newly created resource
    // cannot host a registered WebID yet anyway.
    const identifier = representation.metadata.identifier?.value;
    if (identifier) {
      await this.validateCard({ path: identifier }, representation);
    }
    return this.source.addResource(container, representation, conditions);
  }

  public async deleteResource(identifier: ResourceIdentifier, conditions?: Conditions): Promise<ChangeMap> {
    if ((await this.getRegisteredWebIds(identifier)).length > 0) {
      throw new ForbiddenHttpError(
        `The profile card ${identifier.path} cannot be deleted while its WebID is registered to an account.`,
      );
    }
    return this.source.deleteResource(identifier, conditions);
  }

  /**
   * Returns the WebIDs registered on this server whose card is the given document.
   * A WebID is considered if its relative path matches one of the configured
   * `relativeWebIdPaths` and if it is still registered in the {@link WebIdStore}.
   */
  protected async getRegisteredWebIds(identifier: ResourceIdentifier): Promise<string[]> {
    const webIds = new Set<string>();
    for (const relativeWebIdPath of this.relativeWebIdPaths) {
      const hashIndex = relativeWebIdPath.lastIndexOf('#');
      const relativePath = hashIndex >= 0 ? relativeWebIdPath.slice(0, hashIndex) : relativeWebIdPath;
      if (!identifier.path.endsWith(relativePath)) {
        continue;
      }
      const webId = hashIndex >= 0 ? `${identifier.path}#${relativeWebIdPath.slice(hashIndex + 1)}` : identifier.path;
      if (await this.webIdStore.hasWebId(webId)) {
        webIds.add(webId);
      }
    }
    return [ ...webIds ];
  }

  /**
   * Converts the representation of a document to quads, without consuming the
   * original representation, which remains usable by the wrapped store.
   */
  protected async parseToQuads(identifier: ResourceIdentifier, representation: Representation): Promise<Quad[]> {
    const copy = await cloneRepresentation(representation);
    if (copy.metadata.contentType === INTERNAL_QUADS) {
      return arrayifyStream<Quad>(copy.data);
    }
    const converted = await this.converter.handleSafe({
      identifier,
      representation: copy,
      preferences: { type: { [INTERNAL_QUADS]: 1 }},
    });
    if (converted.metadata.contentType !== INTERNAL_QUADS) {
      representation.data.destroy();
      throw new BadRequestHttpError(`Invalid profile card ${identifier.path}: could not be parsed as RDF.`);
    }
    return arrayifyStream<Quad>(converted.data);
  }

  /**
   * Ensures that a write to the card of a registered WebID results in valid RDF
   * that still contains the `solid:oidcIssuer` triple for that WebID.
   */
  protected async validateCard(identifier: ResourceIdentifier, representation: Representation): Promise<void> {
    const webIds = await this.getRegisteredWebIds(identifier);
    if (webIds.length === 0) {
      return;
    }

    let quads: Quad[];
    try {
      quads = await this.parseToQuads(identifier, representation);
    } catch (cause: unknown) {
      representation.data.destroy();
      const message = `Invalid profile card ${identifier.path}: not valid RDF. ${createErrorMessage(cause)}`;
      throw new BadRequestHttpError(message, { cause });
    }

    const valid = webIds.every((webId): boolean =>
      quads.some(({ subject, predicate, object }): boolean =>
        subject.value === webId &&
        predicate.value === SOLID.terms.oidcIssuer.value &&
        object.termType === 'NamedNode' &&
        object.value === `${this.baseUrl}/`));

    if (!valid) {
      representation.data.destroy();
      const expected = [ ...webIds ]
        .map((webId): string => `<${webId}> solid:oidcIssuer <${this.baseUrl}/>`)
        .join(' and ');
      throw new BadRequestHttpError(`Invalid profile card ${identifier.path}: missing the ${expected} triple.`);
    }
  }
}
