name: Typedocs
on:
  workflow_call:

jobs:
  typedocs:
  # Build typedocs and publish them to the GH page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci --ignore-scripts
      - name: Generate typedocs
        run: npm run typedocs
      - name: Get tagged version
        id: version
        uses: battila7/get-version-action@v2
      - name: Deploy typedocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir:  ${{ steps.version.outputs.major }}.x/docs
